// Code generated by "stringer -type=MediaPlayerType -linecomment -output=media_string.go"; DO NOT EDIT.

package models

import "strconv"

const _MediaPlayerType_name = "StillClip"

var _MediaPlayerType_index = [...]uint8{0, 5, 9}

func (i MediaPlayerType) String() string {
	i -= 1
	if i >= MediaPlayerType(len(_MediaPlayerType_index)-1) {
		return "MediaPlayerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MediaPlayerType_name[_MediaPlayerType_index[i]:_MediaPlayerType_index[i+1]]
}
