// Code generated by "stringer -type=VideoSource -linecomment"; DO NOT EDIT.

package models

import "strconv"

const _VideoSource_name = "BlackInput 1Input 2Input 3Input 4Input 5Input 6Input 7Input 8Input 9Input 10Input 11Input 12Input 13Input 14Input 15Input 16Input 17Input 18Input 19Input 20ColorBarsColor 1Color 2MediaPlayer 1MediaPlayer 1 KeyMediaPlayer 2MediaPlayer 2 KeyKey 1 MaskKey 2 MaskKey 3 MaskKey 4 MaskDSK 1 MaskDSK 2 MaskSuperSourceCleanFeed 1CleanFeed 2Auxilary 1Auxilary 2Auxilary 3Auxilary 4Auxilary 5Auxilary 6ME 1 ProgME 1 PrevME 2 ProgME 2 PrevCamera 1 Direct"

var _VideoSource_map = map[VideoSource]string{
	0:     _VideoSource_name[0:5],
	1:     _VideoSource_name[5:12],
	2:     _VideoSource_name[12:19],
	3:     _VideoSource_name[19:26],
	4:     _VideoSource_name[26:33],
	5:     _VideoSource_name[33:40],
	6:     _VideoSource_name[40:47],
	7:     _VideoSource_name[47:54],
	8:     _VideoSource_name[54:61],
	9:     _VideoSource_name[61:68],
	10:    _VideoSource_name[68:76],
	11:    _VideoSource_name[76:84],
	12:    _VideoSource_name[84:92],
	13:    _VideoSource_name[92:100],
	14:    _VideoSource_name[100:108],
	15:    _VideoSource_name[108:116],
	16:    _VideoSource_name[116:124],
	17:    _VideoSource_name[124:132],
	18:    _VideoSource_name[132:140],
	19:    _VideoSource_name[140:148],
	20:    _VideoSource_name[148:156],
	1000:  _VideoSource_name[156:165],
	2001:  _VideoSource_name[165:172],
	2002:  _VideoSource_name[172:179],
	3010:  _VideoSource_name[179:192],
	3011:  _VideoSource_name[192:209],
	3020:  _VideoSource_name[209:222],
	3021:  _VideoSource_name[222:239],
	4010:  _VideoSource_name[239:249],
	4020:  _VideoSource_name[249:259],
	4030:  _VideoSource_name[259:269],
	4040:  _VideoSource_name[269:279],
	5010:  _VideoSource_name[279:289],
	5020:  _VideoSource_name[289:299],
	6000:  _VideoSource_name[299:310],
	7001:  _VideoSource_name[310:321],
	7002:  _VideoSource_name[321:332],
	8001:  _VideoSource_name[332:342],
	8002:  _VideoSource_name[342:352],
	8003:  _VideoSource_name[352:362],
	8004:  _VideoSource_name[362:372],
	8005:  _VideoSource_name[372:382],
	8006:  _VideoSource_name[382:392],
	10010: _VideoSource_name[392:401],
	10011: _VideoSource_name[401:410],
	10020: _VideoSource_name[410:419],
	10021: _VideoSource_name[419:428],
	11001: _VideoSource_name[428:443],
}

func (i VideoSource) String() string {
	if str, ok := _VideoSource_map[i]; ok {
		return str
	}
	return "VideoSource(" + strconv.FormatInt(int64(i), 10) + ")"
}
